@startuml

autonumber
skinparam sequence {
  ParticipantFontSize 12
  ParticipantBorderColor #454545
  ParticipantBackgroundColor White

  LifeLineBorderColor #454545
  ArrowColor #454545
}

participant USER order 1
participant BOOKING order 2
participant CAR order 3
participant HOTEL order 4
participant RPC order 5
participant Saga1_FSM order 6
participant Tx1_FSM order 7
participant Tx2_FSM order 7

box ALPHA #LightBlue
	participant RPC
	participant Saga1_FSM
	participant Tx1_FSM
	participant Tx2_FSM
end box

USER -> BOOKING: request
activate BOOKING

== Saga[1] Transaction Begin ==

BOOKING -> RPC : SagaStartedEvent
activate BOOKING #00CC33
activate RPC
create Saga1_FSM
RPC -> Saga1_FSM: create
note over of Saga1_FSM: IDEL
Saga1_FSM --> RPC
RPC --> BOOKING
deactivate BOOKING
deactivate RPC
BOOKING -> BOOKING

== Tx[1] Transaction ==

BOOKING -> CAR
activate CAR
CAR -> RPC : TxStartedEvent
activate CAR #00CC33
activate RPC
RPC -> Saga1_FSM: TxStartedEvent
activate Saga1_FSM
create Tx1_FSM
Saga1_FSM -> Tx1_FSM: TxStartedEvent
note over of Tx1_FSM: IDEL
Tx1_FSM --> Saga1_FSM
note over of Saga1_FSM: IDEL + TxStartedEvent = PARTIALLY_ACTIVE
Saga1_FSM --> RPC
deactivate Saga1_FSM
RPC --> CAR
deactivate CAR
deactivate RPC
CAR -> CAR: do something
CAR -> RPC : TxEndedEvent
activate CAR #00CC33
activate RPC
RPC -> Saga1_FSM: TxEndedEvent
activate Saga1_FSM
Saga1_FSM -> Tx1_FSM: TxEndedEvent
activate Tx1_FSM
note over of Tx1_FSM: IDEL + TxEndedEvent = COMMITTED
Tx1_FSM --> Saga1_FSM
deactivate Tx1_FSM
note over of Saga1_FSM: PARTIALLY_ACTIVE + TxEndedEvent = PARTIALLY_COMMITTED
Saga1_FSM --> RPC
deactivate Saga1_FSM
RPC --> CAR
deactivate CAR
deactivate RPC
CAR --> BOOKING
deactivate CAR
BOOKING -> BOOKING

== Tx[N] Transaction ==

BOOKING -> HOTEL
activate HOTEL
note over HOTEL #FFAAAA: omega timeout is empty or request timeout > omega timeout
HOTEL -> RPC : TxStartedEvent
activate HOTEL #00CC33
activate RPC
RPC -> Saga1_FSM
activate Saga1_FSM
create Tx2_FSM
Saga1_FSM -> Tx2_FSM
note over Tx2_FSM: IDEL
Tx2_FSM --> Saga1_FSM
note over of Saga1_FSM: PARTIALLY_COMMITTED + TxStartedEvent = PARTIALLY_ACTIVE
Saga1_FSM --> RPC
deactivate Saga1_FSM
RPC --> HOTEL
deactivate HOTEL
HOTEL -> HOTEL
deactivate RPC
HOTEL -> RPC : ?
activate HOTEL #00CC33
activate RPC
RPC -> Saga1_FSM: ?
activate Saga1_FSM
Saga1_FSM -> Tx2_FSM: ?
activate Tx2_FSM
note over Tx2_FSM #FFAAAA: FAILED or COMMITTED
Tx2_FSM -> Saga1_FSM
deactivate Tx2_FSM
note over Saga1_FSM #FFAAAA: PARTIALLY_COMsaga-sequence-hotel-timeout-non-interrupt-exception-scenarioMITTED or FAILED
Saga1_FSM --> RPC
deactivate Saga1_FSM
RPC --> HOTEL
deactivate RPC
deactivate HOTEL
note over HOTEL #FFAAAA : if request timeout exception, the HOTEL state of being uncertain
autonumber 30
HOTEL --[#C70039]> BOOKING : request timeout exception
deactivate HOTEL


== Saga[1] Transaction End ==

activate BOOKING #00CC33
autonumber 36
BOOKING -> RPC : SagaTimeoutEvent
activate RPC
RPC -> Saga1_FSM : SagaTimeoutEvent
activate Saga1_FSM
note over of Saga1_FSM: SUSPENDED
Saga1_FSM --> RPC
deactivate Saga1_FSM
RPC --> BOOKING
deactivate RPC
BOOKING --[#C70039]> USER
deactivate BOOKING

@enduml