@startuml

autonumber
skinparam sequence {
  ParticipantPadding 20
  ParticipantFontSize 12
  ParticipantBorderColor #454545
  ParticipantBackgroundColor White

  LifeLineBorderColor #454545
  ArrowColor #454545
}

participant USER order 1
participant BOOKING order 2
participant CAR order 3
participant HOTEL order 4
participant RPC order 5
participant FSM order 6

box ALPHA #LightBlue
	participant RPC
	participant FSM
end box

USER -> BOOKING: request
activate BOOKING

== Saga Transaction Begin ==

BOOKING -> RPC : SagaStartedEvent
activate BOOKING #00CC33
activate RPC
RPC --> BOOKING
deactivate BOOKING
deactivate RPC
BOOKING -> BOOKING: do something

== Tx[1] Transaction ==

BOOKING -> CAR
activate CAR
CAR -> RPC : TxStartedEvent
activate CAR #00CC33
activate RPC
RPC --> CAR
deactivate CAR
deactivate RPC
CAR -> CAR
CAR -> RPC : TxEndedEvent
activate CAR #00CC33
activate RPC
RPC --> CAR
deactivate CAR
deactivate RPC
CAR --> BOOKING
deactivate CAR
BOOKING -> BOOKING: do something

== Tx[N] Transaction ==

BOOKING -> HOTEL
activate HOTEL
HOTEL -> RPC : TxStartedEvent
activate HOTEL #00CC33
activate RPC
RPC --> HOTEL
deactivate HOTEL
deactivate RPC
HOTEL -> HOTEL
HOTEL -> RPC : TxEndedEvent
activate HOTEL #00CC33
activate RPC
RPC --> HOTEL
deactivate HOTEL
deactivate RPC
HOTEL --> BOOKING
deactivate HOTEL

BOOKING -> BOOKING: do something

== Saga Transaction End ==

BOOKING -[#C70039]>x RPC : SagaEndedEvent
activate BOOKING #00CC33
activate RPC
RPC --[#C70039]> BOOKING
deactivate BOOKING
deactivate RPC

BOOKING -[#C70039]>x RPC : SagaAbortedEvent
activate BOOKING #00CC33
activate RPC
RPC --[#C70039]> BOOKING
deactivate BOOKING
deactivate RPC

BOOKING --[#C70039]> USER: throw exception

@enduml