@startuml

autonumber
skinparam sequence {
  ParticipantPadding 30
  ParticipantFontSize 12
  ParticipantBorderColor #454545
  ParticipantBackgroundColor White

  LifeLineBorderColor #454545
  ArrowColor #454545
}

participant USER order 1
participant BOOKING order 2
participant CAR order 3
participant HOTEL order 4
participant RPC order 5
participant FSM order 6

box ALPHA #LightBlue
	participant RPC
	participant FSM
end box

USER -> BOOKING: request
activate BOOKING

== Saga Transaction Begin ==

BOOKING -> RPC : SagaStartedEvent
activate BOOKING #00CC33
activate RPC
RPC --> BOOKING
deactivate BOOKING
deactivate RPC
BOOKING -> BOOKING

== Tx[1] Transaction ==

BOOKING -> CAR
activate CAR
CAR -> RPC : TxStartedEvent
activate CAR #00CC33
activate RPC
RPC --> CAR
deactivate CAR
deactivate RPC
CAR -> CAR
CAR -> RPC : TxEndedEvent
activate CAR #00CC33
activate RPC
RPC --> CAR
deactivate CAR
deactivate RPC
CAR --> BOOKING
deactivate CAR
BOOKING -> BOOKING

== Tx[N] Transaction ==

BOOKING -[#C70039]>x HOTEL
activate HOTEL
note right of HOTEL #FFAAAA
 13 Must configure timeout, use
 timeout aspect exceptions to
 ensure local transaction integrity
end note
HOTEL --[#C70039]> BOOKING : throw non-hotel exception
note left of HOTEL
 14 Request connection timeout or
 other network exception
end note
deactivate HOTEL
|||

note over BOOKING, HOTEL
We can wait for the same timeout
as the hotel method after catching
a non-hotel exception
end note

... Waiting for the same timeout as the hotel method \n (hotel method has been commit or rollback)  ...

== Saga Transaction End ==

BOOKING -> RPC : RPC
activate BOOKING #00CC33
RPC --> BOOKING
deactivate BOOKING
BOOKING --> USER

loop committed transactions

RPC -> CAR : compensate
activate CAR #00CC33
CAR -> CAR
activate CAR
deactivate CAR
CAR --> RPC
deactivate CAR

RPC -> HOTEL: compensate
note left RPC
  18 If the hotel method has been committed
  the compensation will be called
end note
activate HOTEL #00CC33
HOTEL -> HOTEL: cancel something
activate HOTEL
deactivate HOTEL
HOTEL --> RPC
deactivate HOTEL

end

@enduml