@startuml
scale 300 width
hide empty description

[*] --> IDEL : TXStartedEvent
IDEL --> COMMITTED : TXEndedEvent
IDEL --> FAILED : TXAbortedEvent
COMMITTED --> COMPENSATED : TxCompensateEvent
COMMITTED --> [*]
FAILED --> [*]
COMPENSATED --> [*]

@enduml
